apiVersion: v1
kind: Secret
metadata:
  name: argo-executor.rollout-sa
  annotations:
    kubernetes.io/service-account.name: argo-executor
type: kubernetes.io/service-account-token
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: rollout
 namespace: argo-ci
rules:
- apiGroups:
    - ""
    - apps
  resources:
    - pods
    - pods/exec
    - pods/log
    - deployments
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rollout-binding
  namespace: app-name
subjects:
- kind: ServiceAccount
  name: argo-executor
roleRef:
  kind: ClusterRole
  name: rollout
  apiGroup: rbac.authorization.k8s.io