kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: app-name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/user/app-name'
    path: deploy/kustomize/production
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app-name
  syncPolicy:
    automated: {}

---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: app-name-argoci
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/user/app-name'
    path: deploy/argoci
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app-name
  syncPolicy: 
    automated: {}
---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: app-name-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/user/app-name'
    path: deploy/argocd
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app-name
  syncPolicy: 
    automated: {}
