apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yaml
  ## generate repository only first time
  ## and comment out for ArgoCD
  #- repository.yaml 
  - application.yaml

patchesStrategicMerge:
  - argocd-cmd-params-cm-patch.yml
