apiVersion: v1
kind: Secret
metadata:
  name: app-name
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/username/app-name
  password: username
  username: access-token